### ISSUE TITLE
Is there an easy way to preview the new article?

### ISSUE THREAD

**Issue by f-hollow** [espressif/developer-portal#43]
_Originally posted by @tore-espressif in https://github.com/espressif/developer-portal/issues/37#issuecomment-2189391818_

As of now the only way to preview a new article in a PR is:

1. [Check out](https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git) the pull request locally.
2. Make sure you have Hugo installed locally and, in the repo folder, run `hugo server`.

Automate the preview process by building the PR branch with Hugo and deploying it using GitHub Actions:

- [How to automate previews for Github Pages](https://daiyi.co/blog/pr-previews-for-github-pages/#Create-a-new-static-site)
- [Using GitHub Actions to build automagic Hugo previews of draft articles](https://rmoff.net/2022/04/06/using-github-actions-to-build-automagic-hugo-previews-of-draft-articles/)

**Comment by f-hollow** [comment]
To make preview useful, we should be able to change `page_url`, so that we can have multiple versions of the portal for different PRs.

The [standard](https://github.com/actions/deploy-pages) deployment action `actions/deploy-pages`, can only publish to a standard URL `<username>.github.io/<reponame>`. The proposed [workaround](https://github.com/orgs/community/discussions/37267#discussioncomment-4012060) does not work.

<details>

```yml
# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

</details>

The alternative action [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), does [not](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#supported-tokens) work. I tried changing branches, and I always get `remote: Permission to <username>/developer-portal.git denied to github-actions[bot].`

<details>

```yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

</details>

Need to look for other ways to enable preview.
